language: python
python:
- '3.6'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key-e:
    secure: CUHTc9xTyxDx4IMJkV/EidJ1O1h9QgEkh90RBlbms44ONplP/MRW8RBiUgPCUzjkTgd0TZ24qy1Dsk/5aHLctF3P2mYHh6/1ibcnRLRCqqssFQH1SDaGJTyGqcW8t+MlI7hCrVCuenmTWUKOntBrdWlavzsbdVcWyc8IigCobCu0m8zaLeAUWyMhai4Al6u3Hn19V+808C82fsblZVF1ZAT+D6wZ3XDQCWLU7LDL0hjMfUGN2OA1lkdpWtXyqA8AlltbV9cCxCZ0NY3+l+pBcpmuBEUge+kI3SeBx4PSBIKIRM6ndYXY9qrKhOccQh1POyBhsLUXJZGNbyK1uAOApSAC9SKgXIpPc+MvClgWAaCb9cFqIhD6H1qG0ROboP1a9iwtCyApNYx4d8Jn8AAY6uZ3C7OWDcdB5zIN8KitsvP4YbVI802Gf8HJpoxWgpVkOxAPwSVM21FC9ClPcdhXnD/zL9TB9JijfClJTZd3EEtJBOp2NUfEA4ICN2E3cgT4HGnTZBQ94bujxdqSbMbABRrb80sE7L7dAnABW2lvrE3EL6346rwUhv1N1i0ELZ3yVOCC30uq4gfsV/abgLJ6R8YuaniGnD9hYslD66ZG0cpjj0+4asNVXspfVzItUYxLVId44oE396Hd2rAu29QGWEHMsQ5a41KNfFW4ssqNg78=
