language: python
python:
- '3.6'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: En2ngvVXMTd1Cy2no81La9lQJCyaJmLjDbzIkmGAMPFqm4ygHsuAcNxs+F0MX7lrhmUqADUkwHkiU/xbJUNFQ/vg0lCqAqY7BDttjkPw5NrBm2WiAVnPFuRIyPpw34iDtil+qVH2HPGUQZzfId5QdtERIPZlzUb5gGpa66pyuKkQYDDHE1m3MpAZb1X9xvaRkwknTqmwPyzc4C/TcBkeTwu2aEyXinBZhRMokO0o1ip8lBMq6tINZi7RnFsbwQBx3pjYCr/lUE2yr4rbQ4bto9g8Q1Iu3szMjExaxz7ZP7y/VLC4FQjmOfUq4JFUeHIzn6GXe0l0r7K6weYoZt94Is65L/uJdEpKwrOqMb/hUv0bLMZmO8bfsXmbVCXMLg0Ueqnz4yQSJ3fGFZGPjQ5eUiBKwK5rCXv+ppz9GMz4Es5vbVViRK9DFCNwcY/wEe8beNkdBxq90/HMwsuiuvSnDHqjobEMf5aizpmlsFhb53MC/PJZ00LYAFciqUubhrzEqq6bcS3fhsodYmRr3k1lAGZcPJYD0RWiU79/QYDUNkxXvEjKUYDmeaUbZDLaPmNatSkgnAl2H3mVKJp4yfSxy6hjA8HytA3FudG/yOHGK198+DNht761FQ/3iOD7YyUTnLVrkbBsVHGPdWd1a6cXKKXEUHH7Y4Z5M0L18hXrvRE=
  app: Staff-TextbookExchange
  on:
    repo: uva-cs3240-f19/Staff-TextbookExchange
